# These are supported funding model platforms

github: # N/A
patreon: # BlockyArcade
open_collective: # N/A
ko_fi: # N/A
tidelift: # N/A
community_bridge: # N/A
liberapay: # Replace with a single Liberapay username
issuehunt: # N/A
otechie: # N/a
custom: # https://dscgg/blockyarcade
